---
# Input:
#   project_name
#   install_homeroom
# Vars:
#   homeroom_template_path
#   homeroom_app_name
# Output:
#   homeroom_route_url
- name: Deploy homeroom
  vars:
    __homeroom_installed: False
  block:
    - name: "Get homeroom deployment (fact)"
      k8s_facts:
        api_version: "apps.openshift.io/v1"
        kind: DeploymentConfig
        name: "{{ homeroom_app_name }}"
        namespace: "{{ project_name }}"
      register: __homeroom_dc

    - name: "Get homeroom deployment (value)"
      debug: 
        var: __homeroom_dc
        verbosity: 1

    - name: "Is homeroom installed (fact)"
      set_fact:
        __homeroom_installed: "{{ __homeroom_dc.resources[0].status.replicas == 1 | default(false) | bool }}"
      when: __homeroom_dc.resources is defined and (__homeroom_dc.resources|length>0)
    
    - name: Is homeroom installed (value)
      debug:
        var: __homeroom_installed
        verbosity: 1

    - name: Deploy homeroom
      block:
        - name: Create homeroom resources
          shell: >
            oc process -f {{ homeroom_template_path }} \
            --param APPLICATION_NAME="{{ homeroom_app_name }}" | oc apply -n {{ project_name }} -f -
          when: not __homeroom_installed

        - name: Wait for the homeroom to deploy
          command: oc rollout status dc/{{ homeroom_app_name }} -n {{ project_name }}
          when: not __homeroom_installed

        - name: Get homeroom Route
          k8s_facts:
            api_version: "route.openshift.io/v1"
            kind: Route
            name: "{{ homeroom_app_name }}"
            namespace: "{{ project_name }}"
          register: __homeroom_route

        - name: Set homeroom route
          set_fact:
            homeroom_route_url: "https://{{ __homeroom_route.resources[0].spec.host }}"

  when: install_homeroom