---
- name: Check for required parameters
  debug:
    msg: "Run this task/playbook with -v to see more output from the debug messages"

- name: Check for required parameters
  fail:
    msg: "Variable '{{ item }}' has no value but is required"
  when: vars[item] is not defined or vars[item]|trim == ""
  with_items: "{{ required_vars }}"

- name: "Create temporary directory"
  tempfile:
    state: directory
    path: "/tmp/"
  register: tmp_dir

- name: Copy .kube/config to {{ tmp_dir.path }}/kube-config
  copy:
    src: ~/.kube/config
    dest: "{{ tmp_dir.path }}/kube-config"
    remote_src: yes

#
# Get the contents of the workshop
#
- name: Fetch lab content task
  include_tasks: fetch-lab-content.yml

- name: Execute with the correct k8s context
  environment:
    KUBECONFIG: "{{ tmp_dir.path }}/kube-config"
    K8S_AUTH_KUBECONFIG: "{{ tmp_dir.path }}/kube-config"
  block:
  - name: Make sure target project {{ project_name }} exists. If not, create it.
    k8s:
      name: "{{ project_name }}"
      api_version: project.openshift.io/v1
      kind: Project
      state: present
  
  - name: "Set oc client in correct project: {{ project_name }}"
    command: "oc project {{ project_name }}"

  - name: Prepull images task
    include_tasks: prepull-images.yml
    when: images_to_prepull is defined and images_to_prepull | length > 0
  
  - name: Set settings argument if defined
    set_fact:
      settings_args: "--settings={{ settings }}"
    when: settings is defined and settings | trim | length > 0

  - name: Install homeroom task
    include_tasks: deploy-homeroom.yml
    when: install_homeroom

## TODO: PROVIDE HOMEROOM_LINK and other user provided vars

  - name: Deploy workshop
    environment:
      HOMEROOM_LINK: "{{ homeroom_route_url }}"
    block:
    - name: Deploy workshop
      command: "{{ lab_local_dir }}/.workshop/scripts/deploy-spawner.sh {{ settings_args }}"
      args:
        chdir: "{{ lab_local_dir }}"
      register: deploy_cmd

    - name: Show deploy workshop regular output
      debug: 
        var: deploy_cmd.stdout_lines
      when: deploy_cmd.stdout_lines is defined and deploy_cmd.stdout_lines | length > 0

    - name: Show deploy workshop error output
      debug: 
        var: deploy_cmd.stderr_lines
      when: deploy_cmd.stderr_lines is defined and deploy_cmd.stderr_lines | length > 0

  - name: Update homeroom task
    include_tasks: update-homeroom.yml
    when: install_homeroom